[project]
name = "LLM-Utilikit"
version = "0.2.0"
description = "This library is designed to enhance large language model projects by offering a curated set of Python modules that can either serve as a robust starting point for new projects or as plug-and-play components to elevate existing ones. The library offers a rich set of pluggable components and a treasure trove of large language model prompts and templates. The library supports OpenAI, LangChain, HuggingFace, and Pinecone libraries. The README file provides a detailed description of the library's modules, including their functionalities and potential use cases. The README file also includes a mind map image and a GNU Affero GPL license."
authors = [
    {name = "Daethyra", email = "109057945+Daethyra@users.noreply.github.com"},
]
dependencies = [
    "openai>=0.28.1",
    "pinecone-client>=2.2.4",
    "langchain>=0.0.27",
    "transformers>=4.34.1",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "GNU Affero General Public License"}
